### ISSUE TITLE
Doesn't load on safari 10 

### ISSUE THREAD

**Issue by paulmillr** [paulirish/web-feature-availability#2]
fetch() is not present in sf10 — we need a polyfill

**Comment by paulirish** [comment]
thx for reporting man. I was testing in nightly webkit -- whoops.

fixed now https://github.com/paulirish/web-feature-availability/commit/09066b6dc896a22a3c5a29053cae1349215bdbcf

**Comment by paulmillr** [comment]
arrow functions should work nevertheless

Thanks for the tool!
